name: Security Scan

on:
  schedule:
    # Run security scan every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run bandit security scan
      run: |
        poetry run bandit -r teamflow/ -f json -o bandit-report.json
        poetry run bandit -r teamflow/ -f txt
      continue-on-error: true

    - name: Run safety check
      run: poetry run safety check --json
      continue-on-error: true

    - name: Upload bandit results
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit-report.json
